/**
 * Compile the style config into plain CSS.
 *
 * This is a minimal, framework-free stand-in for the satus style generator the
 * pipeline originally plugged into (which compiled the same config into
 * Tailwind v4 `@theme` / `@utility` output). Same contract, smaller output:
 *
 *   styles/config.ts ──▶ css/root.css + css/theme.css + css/typography.css
 *
 * Run: bun run setup:styles (also invoked at the end of `bun run figma:import`)
 */

import * as config from '../styles/config'
import { formatObject, scalingCalc } from './utils'

const banner = `/*
 * THIS FILE IS GENERATED BY setup-styles.ts
 * DO NOT EDIT IT DIRECTLY.
 */`

type Config = typeof config

/** Layout, screens, and motion variables, with fluid vw scaling per breakpoint. */
function generateRoot({
  breakpoints,
  customSizes,
  durations,
  layout,
  screens,
}: Pick<
  Config,
  'breakpoints' | 'customSizes' | 'durations' | 'layout' | 'screens'
>) {
  return `:root {
	--device-width: ${screens.mobile.width};
	--device-height: ${screens.mobile.height};

	${formatObject(layout, ([name, { mobile }]) => {
    if (name === 'columns') return `--columns: ${mobile};`

    return `--${name}: ${scalingCalc(mobile)};`
  })}

	${formatObject(customSizes, ([name, { mobile }]) => `--${name}: ${scalingCalc(mobile)};`)}

	${formatObject(durations, ([name, ms]) => `--${name}: ${ms}ms;`)}

	--layout-width: calc(100vw - (2 * var(--safe)));
	--column-width: calc((var(--layout-width) - (var(--columns) - 1) * var(--gap)) / var(--columns));
}

@media (width >= ${breakpoints.dt}px) {
	:root {
		--device-width: ${screens.desktop.width};
		--device-height: ${screens.desktop.height};

		${formatObject(
      layout,
      ([name, { desktop }]) => {
        if (name === 'columns') return `--columns: ${desktop};`

        return `--${name}: ${scalingCalc(desktop)};`
      },
      '\n\t\t'
    )}

		${formatObject(customSizes, ([name, { desktop }]) => `--${name}: ${scalingCalc(desktop)};`, '\n\t\t')}
	}
}
`
}

/** Raw palette plus per-theme semantic color overrides. */
function generateTheme({ colors, themes }: Pick<Config, 'colors' | 'themes'>) {
  const themeEntries = Object.entries(themes)
  const firstTheme = themeEntries[0]?.[1] ?? {}

  return `:root {
	${formatObject(colors, ([key, value]) => `--color-${key}: ${value};`)}

	${formatObject(firstTheme, ([key, value]) => `--color-${key}: ${value};`)}
}

${formatObject(
  themes,
  ([name, value]) => `[data-theme=${String(name)}] {
	${formatObject(value, ([key, value]) => `--color-${key}: ${value};`)}
}`,
  '\n'
)}
`
}

/** One CSS class per text style, with fluid font sizes per breakpoint. */
function generateTypography({
  breakpoints,
  typography,
}: Pick<Config, 'breakpoints' | 'typography'>) {
  const blocks = Object.entries(typography).map(([name, style]) => {
    const base: string[] = []
    const desktop: string[] = []

    for (const [prop, value] of Object.entries(style)) {
      if (
        typeof value === 'object' &&
        value !== null &&
        'mobile' in value &&
        'desktop' in value
      ) {
        const v = value as { mobile: string | number; desktop: string | number }
        if (prop === 'font-size') {
          base.push(`${prop}: ${scalingCalc(v.mobile as number)};`)
          desktop.push(`${prop}: ${scalingCalc(v.desktop as number)};`)
        } else {
          base.push(`${prop}: ${v.mobile};`)
          desktop.push(`${prop}: ${v.desktop};`)
        }
      } else {
        base.push(`${prop}: ${value};`)
      }
    }

    const desktopBlock = desktop.length
      ? `\n\n@media (width >= ${breakpoints.dt}px) {\n\t.${name} {\n\t\t${desktop.join('\n\t\t')}\n\t}\n}`
      : ''

    return `.${name} {\n\t${base.join('\n\t')}\n}${desktopBlock}`
  })

  return `${blocks.join('\n\n')}\n`
}

export const OUTPUTS = {
  root: 'css/root.css',
  theme: 'css/theme.css',
  typography: 'css/typography.css',
} as const

export function buildStyleSheets() {
  return {
    root: [banner, generateRoot(config)].join('\n\n'),
    theme: [banner, generateTheme(config)].join('\n\n'),
    typography: [banner, generateTypography(config)].join('\n\n'),
  }
}

if (import.meta.main) {
  const sheets = buildStyleSheets()

  await Bun.write(`./${OUTPUTS.root}`, sheets.root)
  await Bun.write(`./${OUTPUTS.theme}`, sheets.theme)
  await Bun.write(`./${OUTPUTS.typography}`, sheets.typography)

  console.log('✓ Style config generated successfully')
}
